version: '3.7'

services:
  pg_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=blacklist
      - POSTGRES_USER=blacklist
      - POSTGRES_PASSWORD=blacklist
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5436:5432"

volumes:
  db: